services:
  # databases
  neo4j:
    image: neo4j:5.10.0-enterprise
    restart: on-failure
    deploy:
      resources:
        limits:
          memory: 10G
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_AUTH=neo4j/testtest
      - NEO4J_db_transaction_timeout=10
      - NEO4J_PLUGINS=["graph-data-science"]

